services:
  mysql:
    container_name: demo_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db_name
      MYSQL_USER: wordpress_db_user
      MYSQL_PASSWORD: wordpress_db_pass
      MYSQL_ROOT_PASSWORD: wordpress_db_pass_root
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "./log/mysql/:/var/log/"
      - "./volumes/mysql/data/:/var/lib/mysql/"
    ports:
      - "3306:3306"
  wordpress:
    container_name: demo_wordpress
    depends_on:
      - mysql
    image: dayan3847/wordpress:dev
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress_db_name
      WORDPRESS_DB_USER: wordpress_db_user
      WORDPRESS_DB_PASSWORD: wordpress_db_pass
      WORDPRESS_DEBUG: '1'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://localhost/');
        define('WP_SITEURL','http://localhost/');
        define('WP_DEBUG_DISPLAY',true);
        define('WP_DEBUG_LOG',true);
        if(!defined('WP_DEBUG_DISPLAY'))define('WP_DEBUG_DISPLAY',true);
        @ini_set( 'display_errors',1);
    volumes:
      - "./log/wordpress/apache2/:/var/log/apache2/"
      - "./volumes/wordpress/.vscode/:/var/www/html/.vscode/"
      - "./volumes/wordpress/my_plugins/my_plugin/:/var/www/html/wp-content/plugins/my_plugin/"
      - "./volumes/wordpress/wp-content/:/var/www/html/wp-content/"
    extra_hosts:
      - "host.docker.internal:host-gateway"
