### Requesting / Generating Token
POST http://localhost/wp-json/jwt-auth/v1/token
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Validating Token
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiaWF0IjoxNzMzOTg1OTIwLCJuYmYiOjE3MzM5ODU5MjAsImV4cCI6MTczMzk4NjUyMCwiZGF0YSI6eyJ1c2VyIjp7ImlkIjoxLCJkZXZpY2UiOiIiLCJwYXNzIjoiYmI1YzRhMGIzNjRjMmUwOTA5Y2EzZmJjOGY0Mjk3ZmIifX19.5_9-3WOXZbjgFv45kmwjGr75P27kWXkFR9eX5GR6I8c
POST http://localhost/wp-json/jwt-auth/v1/token/validate
Authorization: Bearer {{token}}
